### ISSUE TITLE
Implement test for ReceiveBatch in PeekLock mode

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-service-bus-node#100]
- [x] Completing a message removes it from the queue/subscription
- [x] Abandoning a message results in getting the same message from queue/subscription in the next recevieBatch call with incremented delivery count. 
- [x] Abandoning a message 10 times, you get it no more. You can then only get it from the dead letter queue/subscription
- [x] Deferring a message results in not getting the same message again from queue/subscription. The message is then gotten using `receiveDefferedMessages`
- [x] Dead lettering the message results in not getting the same message again from queue/subscription. The message is then gotten only from the dead letter queue
- [ ] Settling a message twice should throw error (Blocked by #74)
- [x] Second ReceiveBatch call while the first one is not done should result in error
- [x] No settling of the message results in getting the same message again (with delivery count incremented) from queue/subscription after the lock duration is expired
- [x] Multiple sequential ReceiveBatch using Queue/Subscription, ensure result from one is not affected by the other 
- [x] Ask for `n` msgs, but queue/subscription only has `m` msgs where m < n. This should return exactly `m` messages. Play with the timeout for new message.
- [x] Cases for which we are not yet sure what the result should be, but we should definitely cover:
     - [x] Complete/Abandon/Deadletter/Defer a message received from recevieDefferedMessage, what is the expectation?
     - [x] Complete/Abandon/Deadletter/Defer a message received from the dead letter queue, what is the expectation?

**Comment by ShivangiReja** [comment]
#74 is tracking this issue : Settling a message twice should throw error (Blocked by #74).
Since other test cases are implemented I'm closing this issue.
