### ISSUE TITLE
Implement test for Lock Renewal in PeekLock  mode

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-service-bus-node#103]
- [x] Receive a msg using ReceiveBatch, wait until its lock expires, completing it now results in error
- [x] Receive a msg using ReceiveBatch, test renewLock()
- [x] Receive a msg using Streaming, disable auto lock renewal, use .renewLock() manually (set maxLockDuration to 0)
- [x] Receive a msg using Streaming, Test auto lock renewal (include the time until which auto lock renewal is suppose to run)
- [x] Auto lock renewal: Dont renew if msg lock expiry time is longer than the configured maxLockDuration

**Comment by ramya-rao-a** [comment]
Done with https://github.com/Azure/azure-sdk-for-js/pull/970
