### ISSUE TITLE
When this will be public and available on npm?

### ISSUE THREAD

**Issue by bebenekmarcin** [Azure/azure-service-bus-node#112]
When this will be public and available on npm?

**Comment by AlexGhiondea** [comment]
Thanks for your interest in this SDK!

We are currently working on it and we are planning to have a preview available early next year. That preview will be available on npm.

**Comment by ramya-rao-a** [comment]
Hey @bebenekmarcin,

We wanted to give you an update that Preview 1 for this library has now been released.
See https://www.npmjs.com/package/@azure/service-bus

We have also moved the project from this repo to https://github.com/Azure/azure-sdk-for-js/tree/master/packages/%40azure/servicebus/data-plane

Please do give the published package a try. If you see any issues, please log them at https://github.com/Azure/azure-sdk-for-js/issues. We appreciate any feedback you have.
