### ISSUE TITLE
Moving the EventHubs SDK to the azure-sdk-for-js repository

### ISSUE THREAD

**Issue by HarshaNalluru** [Azure/azure-service-bus-node#115]
Current location of event-hubs node: [Azure Event Hubs for node.js](https://github.com/Azure/azure-event-hubs-node)

This will be migrated to : [packages/@azure](https://github.com/Azure/azure-sdk-for-js/tree/master/packages/%40azure) (`"packages/@azure"` folder of `"azure-sdk-for-js"` repository)

[[template](https://github.com/Azure/azure-sdk-for-js/tree/master/packages/%40azure/template) is to be taken as the reference]

@AlexGhiondea 
@mikeharder  
@bterlson

**Comment by AlexGhiondea** [comment]
I am going to close this issue for now. We are not going to move the Event Hubs one just yet.

**Comment by HarshaNalluru** [comment]
Oh okay
