### ISSUE TITLE
Differences in template and keyvault of azure-sdk-for-js repo

### ISSUE THREAD

**Issue by HarshaNalluru** [Azure/azure-service-bus-node#117]
- Differences(diffs like dependencies, commands, etc.) between the template and existing data planes (like KeyVault)
- Discrepancies(the commands, basic-dependencies (versions, etcetera)) in `"package.json"`s of all the packages
- Standardization of the all the libraries in [azure-sdk-for-js](https://github.com/Azure/azure-sdk-for-js) repo [packages/@azure](https://github.com/Azure/azure-sdk-for-js/tree/master/packages/%40azure)

@AlexGhiondea 
@mikeharder 
@bterlson

**Comment by AlexGhiondea** [comment]
Closing this as the work is being tracked in #147
