### ISSUE TITLE
Deadletter related properties are not being set when passed to the .deadletter() API

### ISSUE THREAD

**Issue by ramya0820** [Azure/azure-service-bus-node#137]
**Describe the bug**
Deadletter related properties are not being set when passed to the .deadletter() API
Specifically, the properties "deadletterReason" and "deadLetterErrorDescription" are not getting set on the message as expected.

**To Reproduce**
- Invoke .deadletter API as:
brokeredMessage.deadLetter({
      deadletterReason: "Incorrect Recipe type",
      deadLetterErrorDescription: "Recipe type does not  match preferences."
    });
- Upon inspecting the message, the properties are not found on the message.

**Expected behavior**
On passing the properties as described, the properties must persist on the message.

**Additional context**
N/A.

@AlexGhiondea @amarzavery @annatisch 
@ramya-rao-a @ShivangiReja @HarshaNalluru

**Comment by ramya-rao-a** [comment]
> Upon inspecting the message, the properties are not found on the message

Is this after you retrieve the message from the dead letter queue?

**Comment by ramya0820** [comment]
> > Upon inspecting the message, the properties are not found on the message
> 
> Is this after you retrieve the message from the dead letter queue?

Yes

**Comment by AlexGhiondea** [comment]
This has been resolved with #141.
