### ISSUE TITLE
receiveDeferredMessage method error for unpartitioned queues and subscriptions

### ISSUE THREAD

**Issue by ShivangiReja** [Azure/azure-service-bus-node#146]
receiveDeferredMessage(sequenceNumber) method works for partitioned queues/subscriptions but not for unpartitioned ones

*  It might be related to the sequence number that we are parsing for subscription because sequence number contains 3 properties i.e. low, high and unsigned, In case of subscription it always sets high value as 0 but for queue it sets some big random number.

**Comment by ShivangiReja** [comment]
receiveDeferredMessage(SquenceNumber) method only works for partition queue/subscription.

Context:
In non-partitioned entity, the sequence number is a small number, say 1, 2, 3 etc.
In a partitioned entity, the sequence number is a very very long number. It is long because we stamp the partition details in the higher bits of the sequence number. Hence the sequence number becomes really long.

When we request for sequence number, Rhea converts Long number to buffer Array and small number to number and when we call receiveDeferredMessage(SquenceNumber) method Rhea works for buffer Array but not for number!!

**Comment by ramya-rao-a** [comment]
Turns out this was never a problem with the sequence number, but the problem was with the receiver mode which was to be wrapped as unisigned int
