### ISSUE TITLE
Bug in .peek() API (Basic Pricing Tier)

### ISSUE THREAD

**Issue by ramya0820** [Azure/azure-service-bus-node#167]
**Describe the bug**
Passing the number of messages parameter to .peek() doesn't work. It's always returning just one message when using "Basic" pricing tier (queue) but is working fine when using a "Premium" pricing tier queue.

**To Reproduce**
- send 5 (two or more) messages to basic queue
- use .peek() API by passing in a number (in this case, 5)
- Only one message gets peeked.

**Expected behavior**
All messages are expected to be peeked based on passed numerical parameter.
Or, an appropriate error message needs to be returned.

**Additional context**
Debugged code to see if in case the data was not being passed to the underlying AMQP client, it seems to be getting passed as expected.

**Comment by ramya0820** [comment]
Unable to replicate error, might have missed something out earlier.

**Comment by ramya-rao-a** [comment]
@ramya0820 I just confirmed that this works as expected for unpartitioned queues in the Basic tier.

The fact that `peek()` always gives single message for partitioned queues is explained in https://github.com/Azure/azure-sdk-for-js/issues/1108
