### ISSUE TITLE
Tests for Boolean/SQL/Correation Topic filters

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-service-bus-node#172]
Boolean filters:

- [x] A subscription with default filter should receive all messages sent via the topic
- [x] A subscription with false boolean filter shouldnt receive any messages sent via the topic

SQL filters:
- [ ] A subscription with a SQL rule filter on one of the message properties should work as expected (not sure if this will work, need to test it out)
- [ ] A subscription with a SQL rule filter on one of the custom properties should work as expected
- [ ] A subscription with a SQL rule filter using the AND operator should work as expected
- [ ] A subscription with a SQL rule filter using the OR operator should work as expected
- [ ] A subscription with a SQL rule filter and an action should update the message accordingly

Correlation filters:
- [ ] A subscription with correlation filter on the message properties should work as expected
- [ ] A subscription with correlation filter on the custom properties should work as expected
- [ ] A subscription with correlation filter and a SQL action should update the message accordingly (Not sure if this will work, need to test it out

**Comment by ramya-rao-a** [comment]
@ShivangiReja Try AND in actions as well. Update one property to a string, the other to a number

**Comment by ShivangiReja** [comment]
@ramya-rao-a  @HarshaNalluru 

`UPDATE Customers
SET ContactName = 'Alfred Schmidt', City= 'Frankfurt'
WHERE CustomerID = 1;`

This is a query for update in SQL. I tried both "AND' operator and "," to SET multiple values in action:

`await subscriptionClient.addRule(
      "SqlRuleWithAction",
      "color='blue'",
      "SET quantity = 20,  priority = 'HIGH'"
    );`

`await subscriptionClient.addRule(
      "SqlRuleWithAction",
      "color='blue'",
      "SET quantity = 20 and priority = 'HIGH'"
    );`


but I was getting this error:

**InternalServerError**: The service was unable to process the request; please retry the operation. For more information on exception types and proper exception handling, please refer to http://go.microsoft.com/fwlink/?LinkId=761101 Reference:003f1290-ce91-4145-b9fe-33a3f95132d6, TrackingId:9c09b5fa-199b-8345-823d-cc5d9f05e86f_G35, SystemTracker:NoSystemTracker, Timestamp:2019-01-17T19:59:29

**Comment by ramya-rao-a** [comment]
This is done with #208 

Conclusion on actions:
- Actions using Custom properties work just file
- Actions using System properties works on messages randomly if using Standard pricing
- Actions using System properties works on messages on a new subscription the first time if using Premium pricing
