### ISSUE TITLE
Simplify the scheduleMessages function to schedule all msgs at a single later time

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-service-bus-node#173]
We have the `scheduleMessage` api that allows user to schedule a later time for sending a message.

Correspondingly, we have a `scheduleMessages` which is meant to allow user to schedule multiple messages to be sent at a later time. Here each message can be sent at a different time which forces user to create a new object `ScheduleMessage` which is nothing but another json object with the actual message and the queue time.

The signature is different for `scheduleMessages` when compared to `scheduleMessage` and we now have to export yet another type

A much simpler API is to send all given messages at given time which is what the Go and Python SDKs are doing. This way the signature will also stay similar to `scheduleMessage`

**Comment by ramya-rao-a** [comment]
@bterlson thoughts?

**Comment by ramya-rao-a** [comment]
An even simpler api would be to combine the `scheduleMessage` and `scheduleMessages` to 
`function scheduleMessage(scheduleTime, ...messages)`

**Comment by bterlson** [comment]
I like `scheduleMessages` with a rest parameter for all the messages, that makes a lot of sense.

But it seems like the other API is still needed to support scheduling many messages at different times?

Can you link me to what python/go are doing?

**Comment by ramya-rao-a** [comment]
> support scheduling many messages at different times

I wonder if we should do this at all

Go and Python support multiple message scheduling but not at different times

.Net SDK doesn't support scheduling of multiple messages at all

**Comment by bterlson** [comment]
Sounds like we can assume the functionality isn't super important, so I fully support the simpler design!

**Comment by ramya-rao-a** [comment]
Done with #188
