### ISSUE TITLE
package.json "main" entry point to non existing module

### ISSUE THREAD

**Issue by saasrack** [Azure/azure-service-bus-node#199]
**Describe the bug**
In the packag.json the "main" points to ./dist/lib/index.js causing "No Module Found". The lib folder does not exists. Using "./dist/index.js" in the main the module import works fine.

**To Reproduce**
npm install git://github.com/Azure/azure-service-bus-node.git

Example:
import {OnMessage} from '@azure/service-bus';

**Expected behavior**
Module "@azure/service-bus" should be found

**Package-version**:  @azure/service-bus@0.1.0
**node.js version**: 10.6.0

**Comment by AlexGhiondea** [comment]
@saasrack I believe you need to build the code first (that will run rollup among other things) which will produce the `dist/lib/index.js` file.

Once we publish the package to npmjs you should be able to use the package directly.

**Comment by saasrack** [comment]
@AlexGhiondea It was working in the first place. The index.js is being placed in the `dist/` folder instead in the `dist/lib/`. 

The rollup.base.config.js is configured to place the `index.js` in the `dist/` folder 
`output: { file: "dist/index.js", format: "cjs", sourcemap: true }`
https://github.com/Azure/azure-service-bus-node/blob/master/rollup.base.config.js#L19
