### ISSUE TITLE
There are some warnings, when running npm run units.

### ISSUE THREAD

**Issue by ShivangiReja** [Azure/azure-service-bus-node#201]
**Describe the bug**

dist-esm/test/**/*.spec.js → test-dist/index.js...
(!) Unresolved dependencies
https://rollupjs.org/guide/en#warning-treating-module-as-external-dependency
fs (imported by node_modules\dotenv\lib\main.js,  commonjs-external:fs)
path (imported by node_modules\dotenv\lib\main.js,  commonjs-external:path)
(!) Circular dependency: node_modules\chai\lib\chai.js -> node_modules\chai\lib\chai\utils\index.js -> node_modules\chai\lib\chai\utils\addProperty.js -> node_modules\chai\lib\chai.js
(!) Circular dependency: node_modules\chai\lib\chai.js -> node_modules\chai\lib\chai\utils\index.js -> node_modules\chai\lib\chai\utils\addProperty.js ->  commonjs-proxy:C:\Users\shreja\azure-service-bus-node\node_modules\chai\lib\chai.js -> node_modules\chai\lib\chai.js
(!) Circular dependency: node_modules\chai\lib\chai.js -> node_modules\chai\lib\chai\utils\index.js -> node_modules\chai\lib\chai\utils\addMethod.js -> node_modules\chai\lib\chai.js
(!) Circular dependency: node_modules\chai\lib\chai.js -> node_modules\chai\lib\chai\utils\index.js -> node_modules\chai\lib\chai\utils\overwriteProperty.js -> node_modules\chai\lib\chai.js
(!) Circular dependency: node_modules\chai\lib\chai.js -> node_modules\chai\lib\chai\utils\index.js -> node_modules\chai\lib\chai\utils\overwriteMethod.js -> node_modules\chai\lib\chai.js
(!) Circular dependency: node_modules\chai\lib\chai.js -> node_modules\chai\lib\chai\utils\index.js -> node_modules\chai\lib\chai\utils\addChainableMethod.js -> node_modules\chai\lib\chai.js
(!) Circular dependency: node_modules\chai\lib\chai.js -> node_modules\chai\lib\chai\utils\index.js -> node_modules\chai\lib\chai\utils\overwriteChainableMethod.js -> node_modules\chai\lib\chai.js
created test-dist/index.js in 1.3s

**Comment by ramya-rao-a** [comment]
Fixed with #209
