### ISSUE TITLE
Can I use this with Azure functions?

### ISSUE THREAD

**Issue by wobeng** [Azure/azure-service-bus-node#220]
```
(function (exports, require, module, __filename, __dirname) { import {OnMessage} from '@azure/service-bus';
                                                              ^^^^^^

SyntaxError: Unexpected token import
```

Im using node 8.11.1

**Comment by AlexGhiondea** [comment]
@wobeng can you tell us more about how you are trying to use the library?

**Comment by wobeng** [comment]
I'm new to node so forgive me in advance. I'm trying to use azure-service-bus-node because of its  AMQP  ability, however I'm use to 

```
const azure = require('azure');
const serviceBusService = azure.createServiceBusService();
...and so on
```

I understand azure-service-bus-node uses "import" instead of "require" however when I do

```
import {OnMessage} from '@azure/service-bus'

```

I get the error

```
(function (exports, require, module, __filename, __dirname) { import {OnMessage} from '@azure/service-bus';
                                                              ^^^^^^
SyntaxError: Unexpected token import

```

a quick googling said "import" is not supported by NodeJS by default. if that is so, how can this package be used with nodejs

**Comment by AlexGhiondea** [comment]
Thanks for the additional information.

Can you share more about how you are trying to use the package? How are you adding a reference to it in your application? Have you looked at the samples we have in this repo?

**Comment by wobeng** [comment]
first I ran this
```
npm install git://github.com/Azure/azure-service-bus-node.git
```
and I got the output below and node_modules creation:

```
[wobeng@ip-192-168-1-6 ca-scheduler]$ npm install git://github.com/Azure/azure-service-bus-node.git

> @azure/service-bus@0.1.0 prepack /users/wobeng/.npm/_cacache/tmp/git-clone-2030bad1
> npm i && npm run build

added 247 packages from 710 contributors and audited 898 packages in 4.105s
found 0 vulnerabilities


> @azure/service-bus@0.1.0 prebuild /users/wobeng/.npm/_cacache/tmp/git-clone-2030bad1
> rimraf dist && rimraf typings


> @azure/service-bus@0.1.0 build /users/wobeng/.npm/_cacache/tmp/git-clone-2030bad1
> npm run tslint && tsc -p . && rollup -c


> @azure/service-bus@0.1.0 tslint /users/wobeng/.npm/_cacache/tmp/git-clone-2030bad1
> tslint -p . -c tslint.json


dist-esm/lib/index.js → dist/index.js...
created dist/index.js in 688ms

> @azure/service-bus@0.1.0 prepack /users/wobeng/.npm/_cacache/tmp/git-clone-bd50ee27
> npm i && npm run build

added 247 packages from 710 contributors and audited 898 packages in 4.023s
found 0 vulnerabilities


> @azure/service-bus@0.1.0 prebuild /users/wobeng/.npm/_cacache/tmp/git-clone-bd50ee27
> rimraf dist && rimraf typings


> @azure/service-bus@0.1.0 build /users/wobeng/.npm/_cacache/tmp/git-clone-bd50ee27
> npm run tslint && tsc -p . && rollup -c


> @azure/service-bus@0.1.0 tslint /users/wobeng/.npm/_cacache/tmp/git-clone-bd50ee27
> tslint -p . -c tslint.json


dist-esm/lib/index.js → dist/index.js...
created dist/index.js in 671ms
npm WARN ca-scheduler@0.0.1 No description
npm WARN ca-scheduler@0.0.1 No repository field.
npm WARN ca-scheduler@0.0.1 No license field.

+ @azure/service-bus@0.1.0
added 79 packages from 123 contributors and audited 456 packages in 34.972s
found 0 vulnerabilities

```

I then created test.js to test things

```
import {OnMessage} from '@azure/service-bus';
```

When I run ``` /usr/bin/node test.js ``` . I am expecting nothing but I get this error output
```
(function (exports, require, module, __filename, __dirname) { import {OnMessage} from '@azure/service-bus';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3

Process finished with exit code 1
```

**Comment by AlexGhiondea** [comment]
@wobeng did you take a look at our samples by any chance? They might be able to help get you started -- and if they don't, please let me know.

**Comment by wobeng** [comment]
Hi @AlexGhiondea , I did multiple times, that is why I'm asking here?

**Comment by AlexGhiondea** [comment]
@bterlson can you help @wobeng ?

**Comment by bterlson** [comment]
@wobeng I think the issue here is that Node doesn't support ECMAScript 6 module syntax yet (see [docs](https://nodejs.org/api/esm.html) for how to enable if you like, but do note the highly experimental nature of it).

So, you have two options:

1. Use CommonJS syntax instead of ES6 modules (`const onMessage = require('@azure/service-bus').onMessage`). This should hopefully unblock you immediately.
2. Use TypeScript or Babel to compile your ES6 module syntax to CJS syntax. This may require some more work on your part to adopt these tools into your build pipeline.

Let me know if either of these work for you!

**Comment by wobeng** [comment]
worked :)

Thank you @bterlson  and @AlexGhiondea

**Comment by ramya-rao-a** [comment]
Hey @wobeng,

Hey @gcstarr,

We wanted to give you an update that Preview 1 for this library has now been released.
See https://www.npmjs.com/package/@azure/service-bus

We have also moved the project from this repo to https://github.com/Azure/azure-sdk-for-js/tree/master/packages/%40azure/servicebus/data-plane

Please do give the published package a try. If you see any issues, please log them at  https://github.com/Azure/azure-sdk-for-js/issues. We appreciate any feedback you have.
