### ISSUE TITLE
Tests for Session Manager

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-service-bus-node#225]
**Multiple Sessions**
- Repeat the tests for streaming receiver (other than the auto lock renewal and the reconnecting ones) in #46 when using the session manager
- Reduce the maxConcurrentAcceptSessionRequests to much less than the number of messages in Queue/Subscription and ensure messages from all sessions are received

**Comment by AlexGhiondea** [comment]
Issue moved to [Azure/azure-sdk-for-js #1474](https://github.com/Azure/azure-sdk-for-js/issues/1474) via [**ZenHub**](https://www.zenhub.com/)
