### ISSUE TITLE
receiveBatch should support onError error handler to enable autoComplete and auto lock renew

### ISSUE THREAD

**Issue by amarzavery** [Azure/azure-service-bus-node#23]
Today the `receiveBatch()` method on the [Queue/Subscription]Client looks like this
```ts
receiveBatch(maxMessageCount: number,
    maxWaitTimeInSeconds?: number,
    maxMessageWaitTimeoutInSeconds?: number): Promise<ServiceBusMessage[]>
```

In the current implementation `autoComplete` and `maxAutoRenewDurationInSeconds` are applicable only for streaming receive `client.receive()` scenario. It would be nice to make these features available for receiveBatch() as well.

The contract of `receiveBatch()` is to return a list of messages. Once the list is returned the call to receiveBatch completes. Now if an error occurs while renewing the lock in the background or while autocompleting the message in the background how do you let the customer know about it?

To solve the problem of error notification, we can modify the receiveBatch signature to be as follows:
```ts
export interface BatchReceiveOptions {
  maxWaitTime?: number;
  maxMessageWaitTimeout?: number;
  autoCompelete?: boolean;
  maxAutoRenewDurationInSeconds?: number;
}
export type OnError = (error: MessagingError | Error) => void;

receiveBatch(onError: OnError, maxMessageCount: number, options?: BatchReceiveOptions): Promise<ServiceBusMessage[]>
```
 
- Now auto lock renewal  and autoComplete can happen in the background.
- Techncially we don't need a logical point like completion of customer's message handler to stop auto lock renewal. Stopping autoLock renewal whenever an attempt is made to settle the message is good enough.
- If we do it like this then receiveBatch can have autoComplete and AutoLockRenew as well

Again those would be optional parameters and customers can  always decide to do to complete the message and renew locks by themselves if that is what they actually need.

IMHO, this flavor of receiveBatch will find more consumers. It provides an option to do the grunt work of message completion and auto lock renewal for the customer, thereby letting the customer focus on message processing.

**Comment by AlexGhiondea** [comment]
I think this is something we should consider!

The thing that I would do is change the signature of the method to put the error handler at the end:
receiveBatch(maxMessageCount: number, options?: BatchReceiveOptions, onError: OnError): Promise<ServiceBusMessage[]>

**Comment by ramya-rao-a** [comment]
Though having autoComplete and autoLockRenewal is a good to have feature, for the scope of v1, I believe we should stay in sync with what the .Net SDK is doing. Go and Python are not planning to implement these either.

I would suggest to close this issue for now. Then based on user feedback and further discussions with SDKs of other languages, we can revisit this.

**Comment by ramya-rao-a** [comment]
Closing this for now.
We will revisit once we have user feedback
