### ISSUE TITLE
Issue with receiveDeferredMessage() 

### ISSUE THREAD

**Issue by ramya0820** [Azure/azure-service-bus-node#230]
The API is now failing, though it was working fine earlier.
Need to investigate what breaking changes need to be undone.

**Comment by HarshaNalluru** [comment]
@ramya0820 
Initiated a PR(https://github.com/Azure/azure-service-bus-node/pull/227) to resolve an issue with `receiveDeferredMessages()`. **- Not merged yet.**
Is this what you are referring to ?

**Comment by ramya0820** [comment]
So the issue got introduced due to a different thing we were trying and using the scheduleTime property on messages. Undoing the changes got sample working as expected. Closing this for now as the problem is different (will create a different, more precise test-case for it when ready).
