### ISSUE TITLE
Specify messageId or broker properties when scheduling message 

### ISSUE THREAD

**Issue by wobeng** [Azure/azure-service-bus-node#237]
Hi

Is it possible to specify messageId or broker properties when scheduling message

**Comment by ramya-rao-a** [comment]
Yes, it should be. When creating the message that you want to send you can set the messageId and other properties just like you would do when sending the message. 
https://github.com/Azure/azure-service-bus-node/blob/master/lib/serviceBusMessage.ts#L123 points to the interface of the message
