### ISSUE TITLE
Implement the session client

### ISSUE THREAD

**Issue by amarzavery** [Azure/azure-service-bus-node#4]
- [ ] Add support for session operations on the $management endpoint. Documentation can be found [here](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-amqp-request-response#session-operations)
   - [ ] Session Renew Lock
   - [ ] Peek Session Message
   - [ ] Set Session State
   - [ ] Get Session State
   - [ ] Enumerate Sessions
- [ ] Send messages in a session
- [ ] Receive messages in a session

Take a look at the [.net implementation](https://github.com/Azure/azure-service-bus-dotnet/blob/dev/src/Microsoft.Azure.ServiceBus/ISessionClient.cs). They have a SessionClient that implements the ISessionClient interface. This interface has different flavors of `AcceptMessage` method that accepts optional sessionId and optional operationTimeout and returns a MessageSession object.

The [MessageSession](https://github.com/Azure/azure-service-bus-dotnet/blob/dev/src/Microsoft.Azure.ServiceBus/MessageSession.cs) object has methods to setSessionState(), getSessionState(), renewSessionLock, etc.

Not sure if that suites our design. I think having an optional sessionId property on MessageSender, MessageReceiver and the ManagementClient should do the trick for us. Haven't given a deeper thought at it.

**Comment by ramya-rao-a** [comment]
Adding a note here that the same has to be done for both queues and subscriptions.

**Comment by ramya-rao-a** [comment]
Closing this issue as we now have the session related features for Queue checked in

cc @AlexGhiondea
