### ISSUE TITLE
Implement integration tests for basic send/receive, message settling and lock renewal scenarios

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-service-bus-node#46]

**Comment by ramya-rao-a** [comment]
Tests that need mocks

**Reconnect**
- Reconnect receiver link on message receive failure 
- Reconnect on session failure
- Reconnect on connection failure
- No reconnect on non-retryable errors
- No reconnect for batching receivers

**Comment by annatisch** [comment]
Hi @ramya-rao-a, @amarzavery  - I just did a test for this scenario:
```
No settling of message results in an expired message. Should this increment the delivery count the next time?
```
And I can confirm that this does indeed increment the delivery count - which should protect us from messages that crash the client so long as the client can recover itself.

**Comment by AlexGhiondea** [comment]
Thank you for breaking down this work! I have created separate issues for this work.
