### ISSUE TITLE
Implement integration tests for Sessions

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-service-bus-node#47]

**Comment by ramya-rao-a** [comment]
**Single Session**
- Repeat the tests (other than the auto lock renewal and the reconnecting ones) in #46 for a single session after using `acceptSession()`
- `acceptSession()` with sessionId should return messageSession for receiving messages from that session. Test both streaming and batching receivers
- `acceptSession()` with non existing sessionId should return with empty results for receiveBatch
- `acceptSession()` with no sessionId, should return with empty results for receiveBatch when the queue/subscription has no messages with sessionId
- `acceptSession()` with no sessionId, should return with results from the queue/subscription which has messages from a single session. Test both streaming and batching receivers
- `acceptSession()` with no sessionId, should return with results (random session chosen) from the queue/subscription which has messages from a multiple session. Test both streaming and batching receivers

**Multiple Sessions**
- Repeat the tests for streaming receiver (other than the auto lock renewal and the reconnecting ones) in #46 when using the session manager
- Reduce the maxConcurrentAcceptSessionRequests to much less than the number of messages in Queue/Subscription and ensure messages from all sessions are received

**Topic Filters: Get Rules**

- Subscription with 0/1/multiple rules returns rules as expected
- Default rule is returned for the subscription for which no rules were added
- Rule with SQL filter returns expected filter expression
- Rule with SQL filter and action returns expected filter and action expression
- Rule with Correlation filter returns expected filter
- Rule with Correlation filter and action (Is this allowed?) returns expected filter and action expression

**Topic Filters: Add Rule**

Positive Test Cases 
- Add Rule with Boolean filter 
- Add Rule with SQL filter 
- Add Rule with SQL filter and action 
- Add Rule with Correlation filter 
- Add Rule with Correlation filter and action (Is this allowed?) 
- Add Default rule on a subscription that its default rule removed 
  
Negative Test Cases 
- Adding a rule with a name which matches with existing rule 
- Adding a rule with no name  
- Adding a rule with no filter 
- Adding a rule with a SQL filter whose input is not a string or is an empty string 
- Adding a rule with a Boolean filter whose input is not Boolean 
- Adding a rule with a SQL action whose input is not a string


**Topic Filters: Remove Rule**
- Removing non existing rule on a subscription that doesnt have any rules should throw error
- Removing non existing rule on a subscription that has other rules should throw error
- Removing existing rule on a subscription

**Comment by HarshaNalluru** [comment]
Currently, 
`acceptSession()` with non-existing sessionId results in a timeout error both for Queues and Subscriptions.
`acceptSession()` with no sessionId(empty string) also results in a timeout error.

@ramya-rao-a

**Comment by ramya-rao-a** [comment]
Done with #978
