### ISSUE TITLE
Implement ManagingEntities sample

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-service-bus-node#70]
https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/ManagingEntities

**Comment by AlexGhiondea** [comment]
This is currently blocked as we haven't yet implemented support for the management plane (That work is tracked by #48)

**Comment by ramya-rao-a** [comment]
Closing this as it is not in immediate scope. 

Added a note https://github.com/Azure/azure-sdk-for-js/issues/1057#issuecomment-461286126 to include samples as part of that epic
