### ISSUE TITLE
Implement TransactionsAndSendVia sample

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-service-bus-node#71]
https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/TransactionsAndSendVia

**Comment by ramya-rao-a** [comment]
@AlexGhiondea Since we dont plan to implement the Transaction support in v1, I would suggest to close this issue as "out of scope" or something similar

**Comment by AlexGhiondea** [comment]
Sounds good.
