### ISSUE TITLE
Move the template for a Node/JS library into the right repo

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-service-bus-node#75]

**Comment by HarshaNalluru** [comment]
Ported the template folder from the repo(https://github.com/Azure/azure-sdk-js), studied the workflow and checked that it builds and passes the tests.
Here's the pull request.
https://github.com/Azure/azure-sdk-for-js/pull/817

**Comment by AlexGhiondea** [comment]
@HarshaNalluru is this change blocked or can we close this issue?

**Comment by HarshaNalluru** [comment]
Successfully merged the template folder, we can close the issue.
