### ISSUE TITLE
Credit Leak in the batchingReceiver

### ISSUE THREAD

**Issue by gcstarr** [Azure/azure-service-bus-node#90]
**Describe the bug**
When calling receiveBatch sequentially on the same client instance, there is a credit leak if the previous batch received less than maxMessageCount. That is, every time we call receiveBatch on an existing client, it will add maxMessageCount to the credit, even if the previous batch timed-out and used no credit.

**To Reproduce**
- Create a queue Client, and call receiveBatch on a queue with no messages, or at least fewer than maxMessageCount.
- Call receiveBatch again. Observe that the value of maxMessageCount is added as credit even though the previous batch did not use that much.

**Expected behavior**
Only the amount of credit needed to maintain receiving maxMessageCount is added.

**Package-version**: Commit 99b6bff
**node.js version**: 10.14.1
**OS name and version**: Ubuntu 18.10

**Comment by gcstarr** [comment]
As mentioned in #91, the batchingReceiver should be using drain to eliminate unneeded credits (and avoid the above-described issue). I spent some time on this today, and while having some limited success unfortunately ran out of time for now.

**Comment by ramya-rao-a** [comment]
@gcstarr, Please see https://github.com/Azure/azure-service-bus-node/issues/81#issuecomment-460897972
