### ISSUE TITLE
Implement tests for Send

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-service-bus-node#99]
- [x] Simple Send and ReceiveBatch in Queue/Topic/Subscription
- [x] SendBatch and ReceiveBatch in Queue/Topic/Subscription
- [x] ScheduleMessage, ScheduleMessages using Queue/Topics/Subscription.

**Comment by ramya-rao-a** [comment]
@ShivangiReja I am adding the test item for cancelling a scheduled message in the above list. So, re-opening this issue

**Comment by AlexGhiondea** [comment]
@ramya-rao-a would it make sense to create a new issue for this?

**Comment by ramya-rao-a** [comment]
I am ok either way. Will create a new issue
